### ISSUE TITLE
PhoneNumberKit.defaultRegionCode not working - Causing provided number to not be valid

### ISSUE THREAD

**Issue by haarj** [sinch/verification-ios-sdk#8]
the "defaultRegionCode" function is not working and is returning a country code of "--", which is then causing the SDK to not validate correct numbers. 

Line -> [Error](https://github.com/sinch/verification-ios-sdk/blob/60c91a83dd75ff3be1accf053042c5a98676d109/Pods/PhoneNumberKit/PhoneNumberKit/PhoneNumberKit.swift#L301)
Is is possible to do something like this?

`func ISOCountryCode() -> String? {
        if #available(iOS 16, *) {
            return Locale.current.region?.identifier.uppercased()
        } else {
            return Locale.current.regionCode.uppercased()
        }
    }
`

I set the `countryIso` of the `PhoneNumberUITextField` and it works now.

**Comment by bguidolim** [comment]
It needs to update the version of PhoneNumberKit.

**Comment by haarj** [comment]
Worked! Thanks!
